"""empty message

Revision ID: 2c63c64d0ef7
Revises: 937ea3f26ad4
Create Date: 2020-03-27 08:36:36.122390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c63c64d0ef7'
down_revision = '937ea3f26ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE "Artist" SET seeking_venue= FALSE WHERE seeking_venue IS NUll;')
    op.execute('UPDATE "Venue" SET seeking_talent= FALSE WHERE seeking_talent IS NUll;')
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
