"""empty message

Revision ID: 69d5d88aa475
Revises: 70c08f27c0e6
Create Date: 2020-03-24 09:05:37.045724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d5d88aa475'
down_revision = '70c08f27c0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE "Artist" SET seeking_venue = FALSE WHERE seeking_venue IS NULL;')
    op.alter_column('Artist', 'seeking_venue', nullable= False)
    # ### end Alembic commands ###

    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
