"""empty message

Revision ID: 89227c6e1a94
Revises: 69d5d88aa475
Create Date: 2020-03-24 09:14:28.805244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89227c6e1a94'
down_revision = '69d5d88aa475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=500), nullable=True))
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
